# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_auto_20170921_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problem',
            old_name='inputs',
            new_name='input_file',
        ),
        migrations.AddField(
            model_name='problem',
            name='output_file',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
