# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0003_auto_20170921_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='outputs',
        ),
    ]
